import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextSessionProvider from "@/components/provider/next-session-provider";
import QueryProvider from "@/components/provider/query-provider";
import { Toaster } from "@/components/ui/sonner";

const interSans = Inter({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${interSans.className}  antialiased`}
      >
        <NextSessionProvider>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
        </NextSessionProvider>
      </body>
    </html>
  );
}
