import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/provider/query/query_provider";
import NextSessionProvider from "@/components/provider/auth/next-session-provider";
import SideberBody from "@/components/sidebar/sidebar-body";

const interSans = Inter({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${interSans.className}  antialiased`}
      >
        <NextSessionProvider>
          <QueryProvider>
            <SideberBody>
              {children}
            </SideberBody>
          </QueryProvider>
        </NextSessionProvider>
      </body>
    </html>
  );
}
